rekenhulp/rekenhulp/urls.py
from django.contrib import admin
from django.urls import path
from RekenhulpApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.rekenhulpVoorblad),
    path('resultaten/', views.resultaten),
    path('sondevoedingen/', views.sondevoedingen),
    path('toevoegen/', views.toevoegen),
    path('bewerken/<str:soort>/', views.bewerken, name="bewerken"),
    path('delete/<str:soort>/', views.delete, name='delete'),
]

rekenhulp/RekenhulpApp/models.py
from django.core.validators import RegexValidator
from django.db import models

alpha = RegexValidator("[A-Za-zÀ-ȕ]", 'Only alphabetic characters')


class Sondevoeding(models.Model):
    Soort = models.CharField(primary_key=True, max_length=50,
                             validators=[alpha])
    Energie = models.DecimalField(max_digits=5, decimal_places=0)
    Eiwit = models.DecimalField(max_digits=5, decimal_places=1)
    Vezels = models.DecimalField(max_digits=5, decimal_places=1)
    Zout = models.DecimalField(max_digits=5, decimal_places=2)
    Natrium = models.DecimalField(max_digits=5, decimal_places=0)
    Vocht = models.DecimalField(max_digits=5, decimal_places=0)

    class Meta:
        db_table = 'sondevoeding'

    def __str__(self):
        return self.Soort

rekenhulp/templates/rekenhulp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sondevoeding Rekenhulp</title>
    {% load static %}
    <script type="text/javascript" src="{% static 'scripts/voorblad.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/voorblad.css' %}">
</head>
<body>
    <div class="menu">
        <a href="/sondevoedingen/">Sondevoedingen</a>
    </div>
    <form method="post">
        {% csrf_token %}
        <div id="container">
            <h1 class="titel">Rekenhulp</h1>
            <div id="inputs">
                <span id="message"></span><br>
                <label class="label" for="naam">Naam:</label>
                <input class="invoer" type="text" id="naam" name="naam" onkeyup="naamCheck()" required autocomplete="off"><br><br>

                <label class="label" for="datum">Geboortedatum:</label>
                <input class="invoer" type="date" id="datum" name="datum" required><br><br>

                <div class="radioboxen">
                    <label class="labelradio1" for="geslacht">Geslacht:</label>
                    <input class="invoerradio1" type="radio" id="vrouw" name="geslacht" value="vrouw" required>
                    <label for="vrouw">Vrouw</label>
                    <input class="invoerradio1" type="radio" id="man" name="geslacht" value="man" required>
                    <label for="man">Man</label><br><br>
                </div>

                <div>
                    <label class="label" for="lengte">Lengte (cm):</label>
                    <input class="invoer" min="40" max="250" type="number" id="lengte" name="lengte" onchange="bmiBerekenen()" required><br><br>

                    <label class="label" for="gewicht">Gewicht (kg):</label>
                    <input class="invoer" min="0" max="1000" type="number" id="gewicht" name="gewicht" onchange="bmiBerekenen()" required><br><br>

                    <div class="dot">
                        <div class="dotText">
                            BMI <br id="break">
                            <span id="bmi-waarde">-</span>
                        </div>
                    </div>
                </div>

                <div class="radioboxen">
                    <label class="labelradio1" for="rust">Rustmetabolisme:</label>
                    <input class="invoerradio1" type="radio" id="who" name="rust" value="WHO" required>
                    <label for="who">WHO</label>
                    <input class="invoerradio1" type="radio" id="h&b" name="rust" value="H&B" required>
                    <label for="h&b">H&B</label><br><br>
                </div>

                <label class="label" for="eiwit">Eiwitaanbeveling:</label>
                <select class="invoerdropdown" id="eiwit" name="eiwit">
                    <option value="0.8">0,8 gram per kg</option>
                    <option value="1.0">1,0 gram per kg</option>
                    <option value="1.2">1,2 gram per kg</option>
                    <option value="1.5">1,5 gram per kg</option>
                </select><br><br>

                <label class="label" for="toeslag">Toeslag voor activiteit en ziekte:</label>
                <select class="invoerdropdown" id="toeslag" name="toeslag">
                    <option value="0">&nbsp;&nbsp;0%</option>
                    <option value="10">10%</option>
                    <option value="20">20%</option>
                    <option value="30">30%</option>
                    <option value="40">40%</option>
                    <option value="50">50%</option>
                </select><br><br>

                <div class="radioboxen">
                    <label class="labelradio2" for="voeding">Sondevoeding:</label>
                    <input class="invoerradio2" type="radio" id="volledig" name="voeding" value="volledig" required>
                    <label for="volledig">Volledig</label>
                    <input class="invoerradio2" type="radio" id="oraal" name="voeding" value="oraal" required>
                    <label for="oraal">Sondevoeding + orale intake</label><br><br>
                </div>

                <label class="labelstart" for="start">Tijd sondevoeding starten:</label>
                <input class="invoerTijd" min="0" max="24" type="number" id="start" name="start" required>
                <label class="labelstop" for="stop">en stoppen:</label>
                <input class="invoerTijd" min="0" max="24" type="number" id="stop" name="stop" required><br><br>


                <label class="label" for="vocht">Vochtbehoefte per 24u (ml):</label>
                <input class="invoer" min="0" max="5000" type="number" id="vocht" name="vocht" required><br><br>

                <label class="label"  for="bijzonderheden">Bijzonderheden:</label>
                <textarea class="invoer" style="resize: none; vertical-align: middle;" id="bijzonderheden" name="bijzonderheden" maxlength="1500" rows="4"></textarea><br><br>


            </div>
            <button class="button disabled" type="submit" id="subknop" name="submit" value="Submit">Submit</button>
        </div>
        <div id="namen">
            <span id="naamtext">Annika Wilbrink, Eveline Verschuren, Noa van Daatselaar en Selena Impink</span>
        </div>
    </form>


</body>
</html>

rekenhulp/templates/resultaten.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sondevoeding Rekenhulp</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/resultaten_style.css' %}">
</head>
<body>
<div class="menu">
  <a href="/" id="rekenhulp-link">Terug naar Rekenhulp</a>
  <a href="/sondevoedingen" id="sondevoeding-link">Sondevoedingen</a>
</div>

<h1 class="titel">Resultaten</h1>

<div id="energie-eiwit">
    <h3 class="text_energie">Energiebehoefte</h3>
    <div class="circle_energie">{{energie}} kcal</div>

    <h3 class="text_eiwit">Eiwitbehoefte</h3>
    <div class="circle_eiwit">{{eiwit}} g p/d</div>

    <h3 class="text_BMI">BMI</h3>
    <div class="circle_BMI">{{bmi}}</div>
</div>

<div id="rust-tabel">
    <table class="rustmetabolismes">
        <thead>
        <tr>
            <th>Rustmetabolisme</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>{{rust}}</td>
        </tr>
        </tbody>
    </table>

</div>


<div id="sondevoeding-tabel">
    <span id="tabel-label">Tabel Sondevoeding</span>
    <div id="checkbox-extra">
        <input type="checkbox" id="extra-sondevoeding" name="extra-sondevoeding" onclick="extra_rijen()">
        <label for="extra-sondevoeding">+Sondevoeding</label>
    </div>

    <form method="post">
        {% csrf_token %}
        <table class="tabel">
            <tr>
                <th></th>
                <th>Soort</th>
                <th>Pompstand</th>
                <th>Totale energie en eiwit pomp</th>
                <th>Handmatige porties</th>
                <th>Totale energie en eiwit portie</th>
                <th>Hoeveelheid sondevoeding</th>
            </tr>
            {% for i in selection %}
                <tr>
                    <td>
                        <input type="hidden" id="rapnaam" style="display: none" value={{rapnaam}}>
                        <input type="hidden" id="pompnaam" style="display: none" value={{pompnaam}}>
                        <input type="hidden" id="portienaam" style="display: none" value={{portienaam}}>
                        <button type="submit" name="maakPDF" value="{{forloop.counter0}}">Maak PDF aan</button>
                    </td>
                    {% for j in i %}
                    <td>{{j}}</td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </table>
    </form>
</div>

</body>
<script>

    window.onload=function(){
        /**
         * Summary. In deze functie worden de PDF's geopend.
         */
        if (document.getElementById('rapnaam').value !== '') {
            window.open('/' + document.getElementById('rapnaam').value);
            window.open('/' + document.getElementById('pompnaam').value);
            window.open('/' + document.getElementById('portienaam').value);
        }
    }

function extra_rijen() {
    /**
     * Summary. Als de checkbox is aangevinkt worden er extra
     * rijen aan de tabel toegevoegd. Wordt de checkbox afgevinkt
     * worden de extra rijen verwijderd.
     */
    let checkbox = document.getElementById('extra-sondevoeding');
    let tables = document.getElementsByTagName('tr');
    if (checkbox.checked) {
        for (let i = 6; i < tables.length; i++) {
            tables[i].style.setProperty('display', 'revert');
        }
    }
    else if (checkbox.checked === false){
        for (let j = 6; j < tables.length; j++) {
            tables[j].style.removeProperty('display')
            tables[j].style.setProperty('display', 'none');
        }
    }
}

</script>
</html>

rekenhulp/templates/sondevoeding.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sondevoeding Rekenhulp</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/sondevoeding.css' %}">
    {% block scripts %}
        <script src="{% static 'scripts/pop-up.js' %}"></script>
    {% endblock scripts %}
</head>
<body>
    <div class="menu">
        <a href="/../">Terug naar rekenhulp</a>
    </div>
    <form method="post">
        {% csrf_token %}
        <div id="container">
            <h1 class="titel">Sondevoedingen</h1>

        <a class="button" href="/toevoegen/">Toevoegen</a>
        <p>Soorten sondevoedingen - per 100 ml</p>
        <div class="column">
            <table>
                <tr>
                    <th>ID</th>
                    <th>Soort</th>
                    <th>Energie (kcal)</th>
                    <th>Eiwit (g)</th>
                    <th>Vezels (g)</th>
                    <th>Zout (g)</th>
                    <th>Natrium (mg)</th>
                    <th>Vocht (ml)</th>
                    <th></th>
                    <th></th>
                </tr>
                {% for regel in tabel %}
                <tr class="data">
                    <td>{{forloop.counter}}</td>
                    <td id="eerste_regel{{forloop.counter}}">{{regel.Soort}}</td>
                    <td>{{regel.Energie}}</td>
                    <td>{{regel.Eiwit}}</td>
                    <td>{{regel.Vezels}}</td>
                    <td>{{regel.Zout}}</td>
                    <td>{{regel.Natrium}}</td>
                    <td>{{regel.Vocht}}</td>
                    <td>
                        <a href="{% url 'bewerken' regel.Soort %}"> <img
                                src="{% static 'img/pencil.png' %}"
                                height ="30" width="30" /></a>
                    </td>
                    <td>
                        <button type="button" id="kruisje" value="{{forloop.counter}}" onclick="annulerenPopUp(true, this.value)"><img src="{% static 'img/cross.png' %}" height ="30" width="30" /></button>

                        <div id="pop-up" class="pop-up">
                            <h1 id="tekst_popup">Weet u zeker dat u wilt verwijderen?</h1>
                            <button type="button" id="annuleren" onclick="annulerenPopUp(false, 1)">Annuleren</button>
                            <span id="test"></span>
                        </div>
                    </td>
                </tr>
                {% endfor %}
                </table>
        </div>
        </div>
        <div id="namen">
            <span id="naamtext">Annika Wilbrink, Eveline Verschuren, Noa van Daatselaar en Selena Impink</span>
        </div>
    </form>
</body>
</html>

rekenhulp/templates/sondevoeding_bewerken.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sondevoeding Rekenhulp</title>
</head>
<body>
bewerken
</body>
</html>

rekenhulp/templates/sondevoeding_toevoegen.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sondevoeding Rekenhulp</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/toevoegen.css' %}">
</head>
<body>
    <div class="menu">
        <a></a>
    </div>
    <form method="post">
        {% csrf_token %}
        <div id="container">
            <h1 class="titel">Sondevoeding</h1>
            <h3 class="ondertitel">{{ondertitel}}</h3>
            <div id="inputs">
                <label class="label" for="id_Soort">{{form.Soort.label}}:</label>
                {{form.Soort}}<br><br>
                <label class="label" for="id_Energie">{{form.Energie.label}} (kcal):</label>
                {{form.Energie}}<br><br>
                <label class="label" for="id_Eiwit">{{form.Eiwit.label}} (g):</label>
                {{form.Eiwit}}<br><br>
                <label class="label" for="id_Vezels">{{form.Vezels.label}} (g):</label>
                {{form.Vezels}}<br><br>
                <label class="label" for="id_Zout">{{form.Zout.label}} (g):</label>
                {{form.Zout}}<br><br>
                <label class="label" for="id_Natrium">{{form.Natrium.label}} (mg):</label>
                {{form.Natrium}}<br><br>
                <label class="label" for="id_Vocht">{{form.Vocht.label}} (ml):</label>
                {{form.Vocht}}<br><br>
            </div>
            <input class="button" type="button" name="Annuleren" value="Annuleren" onclick="window.location.href='/sondevoedingen/'">
            <input class="button" type="submit" name="submit" value="Opslaan">
            <div id="namen">
                <span id="naamtext">Annika Wilbrink, Eveline Verschuren, Noa van Daatselaar en Selena Impink</span>
            </div>
        </div>
    </form>
</body>
</html>